### PR TITLE
Suppress lisk.sh parse error - Closes #186

### LINKED ISSUE #186: lisk.sh status might cause a "parse error"
If PM2 is not running `pm2 jlist` will not produce a valid JSON output but the following:
```
[PM2] Spawning PM2 daemon with pm2_home=/home/lisk/lisk-1.3.0-rc.0-Linux-x86_64/.pm2
[PM2] PM2 Successfully daemonized
[]
```
(everything goes to stdout)

In that case [jq](https://github.com/LiskHQ/lisk-scripts/blob/development/packaged/lisk.sh#L323) will fail with a `parse error`.

### PR DESCRIPTION
**Pull request by Nazgolze**
Suppress parse error when pm2 is not running and check_status function gets called

Closes #186

### CODE REVIEW

File: packaged/lisk.sh [hunk 1]
```diff
@@ -320,16 +320,21 @@ pm2_cleanup() {
...
+		STATUS=1
+	fi
 
-	check_pid
 	if [ "$STATUS" -eq 0  ]; then
 		echo "[+] Lisk is running as PID: $PID"
 		blockheight
 	else
 		echo "[-] Lisk is not running"
+		sync # flush output before exit
```
Comment (fchavant) [inline packaged/lisk.sh]: flush output? won't `sync` write cached writes to disk?

File: packaged/lisk.sh [hunk 2]
```diff
@@ -320,16 +320,21 @@ pm2_cleanup() {
 }
 
 check_status() {
-	PM2_PID="$( pm2 jlist |jq -r ".[] | select(.name == \"$PM2_APP\").pm2_env.pm_pid_path" )"
+	PM2_PID="$( pm2 jlist 2>/dev/null | jq -r ".[] | select(.name == \"$PM2_APP\").pm2_env.pm_pid_path" 2>/dev/null)"
 
-	pm2 describe "$PM2_APP" >> "$SH_LOG_FILE"
+	if [ ! -z "$PM2_PID" ]; then
```
Comment (fchavant) [inline packaged/lisk.sh]:
```suggestion
	if [ -n "$PM2_PID" ]; then
```

**Comment by Nazgolze** [comment]
latest commit should also close #144

File: packaged/lisk.sh [hunk 3]
```diff
@@ -296,6 +296,11 @@ set_logs_paths() {
 }
 
 stop_lisk() {
+	get_status
+	if [ "$STATUS" -ne 0 ] ; then
+		echo "[-] Lisk is not running"
+		exit 1
```
Comment (fchavant) [inline packaged/lisk.sh]: This breaks `coldstart` (and probably any other function calling `stop_lisk()`)

File: packaged/lisk.sh [hunk 4]
```diff
@@ -319,12 +324,19 @@ pm2_cleanup() {
 	pm2 kill
 }
 
-check_status() {
-	PM2_PID="$( pm2 jlist |jq -r ".[] | select(.name == \"$PM2_APP\").pm2_env.pm_pid_path" )"
+get_status() {
+	PM2_PID="$( pm2 jlist 2>/dev/null | jq -r ".[] | select(.name == \"$PM2_APP\").pm2_env.pm_pid_path" 2>/dev/null)"
```
Comment (psychopenguin) [inline packaged/lisk.sh]: you can add the flag -s (silent) to pm2 to avoid printing startup messages :)

```
lisk@fra1-fabio-testnet-01:~/lisk-test$ pm2 kill
[PM2] [-] Stopping Modules
[PM2] [v] Modules Stopped
[PM2] [-] Stopping all Applications
[PM2][WARN] No process found
[PM2] [v] All Applications Stopped
[PM2] [-] Stopping Agent
[PM2] [v] Agent Stopped
[PM2] [-] Stopping PM2 Daemon
[PM2] [-] PM2 Daemon Stopped
lisk@fra1-fabio-testnet-01:~/lisk-test$ pm2 jlist|jq
parse error: Invalid numeric literal at line 1, column 5
lisk@fra1-fabio-testnet-01:~/lisk-test$ pm2 kill
[PM2] [-] Stopping Modules
[PM2] [v] Modules Stopped
[PM2] [-] Stopping all Applications
[PM2][WARN] No process found
[PM2] [v] All Applications Stopped
[PM2] [-] Stopping Agent
[PM2] [v] Agent Stopped
[PM2] [-] Stopping PM2 Daemon
[PM2] [-] PM2 Daemon Stopped
lisk@fra1-fabio-testnet-01:~/lisk-test$ pm2 -s jlist|jq
[]
```
