### PR TITLE
Fix lisk_bridge to overwrite downloaded file - Closes #89

### LINKED ISSUE #89: Issues with lisk_bridge.sh
- usage of `f` flag is not documented
- `installLisk.sh` will not be overwritten if it exists (wget create `installLisk.sh.1` by default) and thus the old script will be used

### PR DESCRIPTION
**Pull request by nazarhussain**
Closes: #89

### CODE REVIEW

File: downloaded/lisk_bridge.sh [hunk 1]
```diff
@@ -77,8 +77,8 @@ if [[ "$BLOCK_HEIGHT" -gt "$TARGET_HEIGHT" ]]; then
 fi
 
 bash "$LISK_HOME/lisk.sh" stop
-rm installLisk.sh
-wget "https://downloads.lisk.io/lisk/$BRIDGE_NETWORK/installLisk.sh"
+rm -rf installLisk.sh
```
Comment (Nazgolze) [inline downloaded/lisk_bridge.sh]: if we're doing wget --no-clobber, there's no need for the rm -rf

File: downloaded/lisk_bridge.sh [hunk 2]
```diff
@@ -45,11 +45,11 @@ fi
 if [[ $SHOW_USAGE ]]; then
 	echo "Usage: $0 <-h <BLOCKHEIGHT>> [-s <DIRECTORY>] [-n <NETWORK>] "
 	echo '-h <BLOCKHEIGHT> -- specify blockheight at which bridging will be initiated'
-	echo '-f <TARBALL> -- Specify local tarball for destination release'
+	echo '-f <TARBALL> -- specify path to local tarball containing the target release'
 	echo '-s <DIRECTORY>   -- Lisk home directory'
 	echo '-n <NETWORK>     -- choose main or test'
 	echo -e '\nExample: bash lisk_bridge.sh -h 50000000 -n test -s /home/lisk/lisk-test'
-	echo -e '\nUse LISK_MASTER_PASSWORD env variable if you want to do secrets migration in non-interactive mode'
+	echo -e '\nSet LISK_MASTER_PASSWORD env variable if you want to do secrets migration in non-interactive mode'
```
Comment (fchavant) [inline downloaded/lisk_bridge.sh]: "Set the* LISK_MASTER_PASSWORD environment* variable [...]"?
