### PR TITLE
Fail on failed blockchain download - Closes #32

### LINKED ISSUE #32: lisk.sh does not fail when restoring fails
I tried to restore a non-existing database. There was an unhandled error during the run of lisk.sh but lisk.sh returned success:

```
$ ./lisk.sh rebuild -0
√ Lisk stopped successfully.
√ Postgresql is running.
√ Postgresql database created successfully.
√ Using Local Snapshot.
Restoring blockchain with /workspace/lisk/var/db/blockchain.db.gz
gzip: /workspace/lisk/var/db/blockchain.db.gz: No such file or directory
√ Blockchain restored successfully.
√ Lisk started successfully.
√ Lisk is running as PID: 7013
Current Block Height:  Unavailable
$ echo $?
0
```

**Expected**

lisk.sh returns non-0 return code when an error occurred.

### PR DESCRIPTION
**Pull request by Nazgolze**
Closes #32 

Well, this covers the example in the issue where it fails to download.
If psql fails, that should be caught. If gunzip fails, if psql somehow succeeds, that will still register as a success as pipefail isn't set

### CODE REVIEW

**Comment by fchavant** [comment]
> If gunzip fails, if psql somehow succeeds, that will still register as a success as pipefail isn't set.
We could set pipefail (for this part of the code)

File: packaged/lisk.sh [hunk 1]
```diff
@@ -337,7 +339,7 @@ check_pid() {
 }
 
 lisk() {
-	node "$(pwd)/bin/lisk"
+	node "$PWD/bin/lisky"
```
Comment (fchavant) [inline packaged/lisk.sh]: Commander's binary is called `lisk`

**Comment by fchavant** [comment]
The plus signs are a little confusing when using `-x`. How about `[+]` instead? or `[ok]` at the end of a line?
